# Author      : Amisha Prashar
# Description : CI/CD Pipeline for building and pushing Docker images to Docker Hub.
# Usage       : Triggered on push to the "main" branch.
# Version     : 1.0.1

name: Lenscorp Workflow

on:
  push:
    branches: [ "main" ] 

jobs:
  Build_and_Push:
    runs-on: ubuntu-22.04

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python (if needed for backend dependencies)
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    # Install Python dependencies (if applicable)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Example: pip install -r backend/requirements.txt

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt update
        sudo apt install docker-compose -y

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push backend image
    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lens-app:backend_${{ github.run_id }} ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lens-app:backend_${{ github.run_id }}

    # Build and push nginx image
    - name: Build and push nginx
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lens-app:nginx_${{ github.run_id }} ./nginx
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lens-app:nginx_${{ github.run_id }}

    # Run the application in detached mode
    - name: Run application
      run: |
        docker-compose up --build -d
